### PR TITLE
Add a way to force a cache miss

### PR DESCRIPTION
**Pull request by jeromedalbert**
Useful for cache warmers if you want to renew the cache.

Similar to `rails`' `ActiveSupport::Cache::Store#fetch`'s [`force: true`](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch) option and `graphql-cache`'s [`force_cache`](https://github.com/stackshareio/graphql-cache/#forcing-the-cache) option.

### CODE REVIEW

**Review by DmitryTsepelev — COMMENTED** [review]
Hi @jeromedalbert! The implementation looks great, but `force_cache` made me think that we force _reading_ from cache instead of skipping it. Maybe we should follow the Rails naming and call it `force`?

**Comment by jeromedalbert** [comment]
Hey @DmitryTsepelev, do you think that the intent would be too cryptic if one just does `MyAppSchema.execute("query { posts { title } }", context: {force: true})`? When reading this it's hard to know that `force` is related to caching. In Rails it's obvious that `force` is related to caching because the word cache is mentioned in the call itself: `cache.fetch('city', force: true)`. But it is not the case when executing a graphql schema, that's why I added the `_cache` in `force_cache` to remove that ambiguity.

I agree it is still ambiguous as to what we're forcing within the cache. To make it fully clear and verbose I am thinking of `force_cache_miss`, `renew_cache`, or `skip_cache`. What do you think? Or are you fine with just `force`?

**Comment by DmitryTsepelev** [comment]
Agreed on the cryptic nature of `force`, I like `renew_cache` 🙂

**Comment by jeromedalbert** [comment]
Sounds good, renamed to `renew_cache`.

**Review by DmitryTsepelev — APPROVED** [review]
LGTM!

**Pull request merged**
