### PR TITLE
first pass at :disabled option

### PR DESCRIPTION
**Pull request by tjk**
Here is a start -- let me know how to improve this please.

### CODE REVIEW

**Comment by DmitryTsepelev** [comment]
Great start! Are you planning to extend `cache_fragment:` field option too?

**Comment by tjk** [comment]
@DmitryTsepelev sorry been a bit busy, will try to update this weekend.

**Comment by jeromedalbert** [comment]
Hi there! 👋 I thought I'd help so I built on your PR and I came up with #61 which I believe should be fully functional.

**Comment by tjk** [comment]
> Hi there! 👋 I thought I'd help so I built on your PR and I came up with #61 which I believe should be fully functional.

Good stuff! Sorry I've been busy and I was able to circumvent this. But thanks for following up, I'll close this one and track yours!

**Pull request closed without merging**
