### PR TITLE
Add union support

### PR DESCRIPTION
**Pull request by DmitryTsepelev**

### CODE REVIEW

**Comment by jeromedalbert** [comment]
I guess that you didn't manage to make this workaround PR work or the specs never passed?

I just realized that my schema is using a few unions in some key parts of our app so I am getting those `Failed to look ahead the field` errors. Since the impacted `cache_fragment:` fields are sometimes used in vastly different queries I don't think I can safely pass `query_cache_key` as a workaround, since the respective fragments could look wildly different and I wouldn't want to cache the wrong fragment.

The internals of graphql-ruby's lookahead are a bit over my head. I tried using https://github.com/rmosolgo/graphql-ruby/pull/3007 's branch in my app but I still got the `Failed to look ahead the field` error. Would this gem need to adapt any code if https://github.com/rmosolgo/graphql-ruby/pull/3007 gets merged as is?

**Comment by DmitryTsepelev** [comment]
The problem is that lookahead does not support unions, and we build a cache key based on it. I feel like it's easier to find a different reliable way to build a key without the lookahead rather than try to fix it's behaviour.

**Comment by hendie** [comment]
Any progress on this PR @DmitryTsepelev ? We also have quite a few instances of unions in our data model. I would love to use your cache offering, but that's kinda limiting us from further evaluation at this time.

**Comment by jeromedalbert** [comment]
FYI I have been using the gem in my codebase and it works as long as I don't cache anything that has unions.

I think another workaround would be to use interfaces instead of unions. Unions and interfaces in GraphQL are very similar, as a union is basically an interface but without shared fields. So it may be possible to migrate with minimal effort for the backend and potentially 0 changes for the API consumer, since the `... on` syntax would still work the same.

I have not verified if this idea works in practice as it was low priority at work (we are lucky that most of the things that need caching don't use unions in our app).

**Pull request closed without merging**
